<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20180803 14:02:19.889" generator="Robot 3.0.4 (Python 2.7.13 on win32)">
<suite source="D:\pip\Case1.robot" id="s1" name="Case1">
<test id="s1-t1" name="Player 1 (x) ชนะเเนวนอนเเถว 1">
<kw name="เปิดหน้าเว็ปเกมส์ OX">
<kw name="Open Browser">
<arguments>
<arg>${URL}</arg>
<arg>${BROWSER}</arg>
</arguments>
<msg timestamp="20180803 14:02:19.921" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" endtime="20180803 14:02:19.921" starttime="20180803 14:02:19.921"></status>
</kw>
<status status="FAIL" endtime="20180803 14:02:19.921" starttime="20180803 14:02:19.919"></status>
</kw>
<status status="FAIL" endtime="20180803 14:02:19.922" critical="yes" starttime="20180803 14:02:19.918">No keyword with name 'Open Browser' found.</status>
</test>
<status status="FAIL" endtime="20180803 14:02:19.927" starttime="20180803 14:02:19.892"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="Case1" pass="0">Case1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20180803 14:02:19.915" level="ERROR">Error in file 'D:\pip\Case1.robot': Importing test library 'SeleniumLbrary' failed: ImportError: No module named SeleniumLbrary
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Windows\SYSTEM32\python27.zip
  c:\python27\DLLs
  c:\python27\lib
  c:\python27\lib\plat-win
  c:\python27\lib\lib-tk
  c:\python27
  c:\python27\lib\site-packages</msg>
</errors>
</robot>
